import type { RouteComponent } from 'vue-router';

export const views: Record<RouterPage.LastDegreeRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import('./_builtin/403/index.vue'),
  404: () => import('./_builtin/404/index.vue'),
  500: () => import('./_builtin/500/index.vue'),
  'constant-page': () => import('./_builtin/constant-page/index.vue'),
  login: () => import('./_builtin/login/index.vue'),
  'not-found': () => import('./_builtin/not-found/index.vue'),
  allplan: () => import('./allplan/index.vue'),
  baseDataMgmt_warningRule: () => import('./baseDataMgmt/warningRule/index.vue'),
  home: () => import('./home/index.vue'),
  notification: () => import('./notification/index.vue'),
  statisticalSearch_createDuration: () => import('./statisticalSearch/createDuration/index.vue'),
  statisticalSearch_distributionDuration: () => import('./statisticalSearch/distributionDuration/index.vue'),
  statisticalSearch_notificationChange: () => import('./statisticalSearch/notificationChange/index.vue'),
  statisticalSearch_powerOutage: () => import('./statisticalSearch/powerOutage/index.vue'),
  statisticalSearch_powerOutagePlan: () => import('./statisticalSearch/powerOutagePlan/index.vue'),
  statisticalSearch_receiveDuration: () => import('./statisticalSearch/receiveDuration/index.vue'),
  statisticalSearch_repeatedPowerOutage: () => import('./statisticalSearch/repeatedPowerOutage/index.vue'),
  system_dataMgmt: () => import('./system/dataMgmt/index.vue'),
  system_functionMgmt_menuMgmt: () => import('./system/functionMgmt/menuMgmt/index.vue'),
  system_functionMgmt_operationMgmt: () => import('./system/functionMgmt/operationMgmt/index.vue'),
  system_functionMgmt_permissionMgmt: () => import('./system/functionMgmt/permissionMgmt/index.vue'),
  system_functionMgmt_resourceMgmt: () => import('./system/functionMgmt/resourceMgmt/index.vue'),
  system_orgMgmt_organizationMgmt: () => import('./system/orgMgmt/organizationMgmt/index.vue'),
  system_orgMgmt_roleMgmt: () => import('./system/orgMgmt/roleMgmt/index.vue'),
  system_orgMgmt_userMgmt: () => import('./system/orgMgmt/userMgmt/index.vue'),
  warningsearch_deliverySuccessWn: () => import('./warningsearch/deliverySuccessWn/index.vue'),
  warningsearch_deliveryTimeoutWn: () => import('./warningsearch/deliveryTimeoutWn/index.vue'),
  warningsearch_planChangeWn: () => import('./warningsearch/planChangeWn/index.vue'),
  warningsearch_repeatedPowerCutWn: () => import('./warningsearch/repeatedPowerCutWn/index.vue'),
  warningsearch_userRefusedWn: () => import('./warningsearch/userRefusedWn/index.vue')
};
