spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://172.16.0.20:3306/bncc?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: bncc_dev
    password: Bncc!@#0627
  flyway:
    enabled: false
    baselineOnMigrate: true
    locations: classpath:db/migration/mysql
  redis:
    host: 172.16.0.23
    port: 6379
    password: Q!w2e3r4t5
    database: 1

tecpie:
  # 是否开启未知参数校验
  failOnUnknownProperties: true
  security:
    # 是否单机服务
    single: false
    # 是否使用当前服务鉴权
    selfAuth: false
    allow:
      # 白名单设置，多个白名单使用,分隔，如不需要进行 tokeswagger-uin 校验，则可将 uri 修改为 /**
      uri: /*/actuator/health,/api/v1/access/**,/swagger-ui.html,/v3/api-docs/**
    server-name: relay-task-service
  logging:
    http:
      method: POST,PUT,DELETE
      notRecordUri: /cache/v1/**,/*/actuator/health,/api/v1/access/**,/swagger-ui.html,/v3/api-docs/**,/doc.html
      respBody: true

