CREATE TABLE `sys_operation_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `trace_id` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT 'traceId',
  `span_id` varchar(20) CHARACTER SET utf8 DEFAULT NULL COMMENT 'spanId',
  `remote_ip` varchar(20) CHARACTER SET utf8 NOT NULL COMMENT '来源ip',
  `request_uri` varchar(100) CHARACTER SET utf8 NOT NULL COMMENT '请求路径',
  `requestMethod` varchar(10) CHARACTER SET utf8 DEFAULT '' COMMENT '请求类型',
  `contentType` varchar(30) CHARACTER SET utf8 DEFAULT '' COMMENT '请求数据类型',
  `requestHeaders` varchar(1024) CHARACTER SET utf8 DEFAULT '' COMMENT '请求头',
  `requestParams` varchar(1024) CHARACTER SET utf8 DEFAULT '' COMMENT '请求参数',
  `requestBody` text COMMENT '请求内容',
  `operation` varchar(255) NOT NULL COMMENT '操作名称',
  `httpStatus` varchar(10) NOT NULL COMMENT '响应编码',
  `responseBody` text COMMENT '响应内容',
  `duration` bigint(20) DEFAULT '0' COMMENT '请求处理时间',
  `remark` varchar(255) DEFAULT '' COMMENT '备注',
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '状态 - 0:停用,1:启用',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除标记 - 0:正常,1:已删除',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '最后更新人',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='操作日志表';