DROP TABLE  IF EXISTS "SYS_LOV";
CREATE TABLE "SYS_LOV"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "CODE" VARCHAR(50) NOT NULL,
    "NAME" VARCHAR(100) NOT NULL,
    "MODULE" VARCHAR(20) DEFAULT 'global',
    "TYPE" INT DEFAULT 0,
    "REMARK" VARCHAR(255) DEFAULT '',
    "STATUS" INT DEFAULT 1 NOT NULL,
    "DELETED" INT DEFAULT 0 NOT NULL,
    "CREATE_BY" BIGINT,
    "CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_BY" BIGINT,
    "UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    NOT CLUSTER PRIMARY KEY("ID"),
    UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYS_LOV" IS 'LOV定义表';
COMMENT ON COLUMN "SYS_LOV"."CODE" IS 'LOV编码';
COMMENT ON COLUMN "SYS_LOV"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_LOV"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "SYS_LOV"."DELETED" IS '是否删除标记 - 0:正常,1:已删除';
COMMENT ON COLUMN "SYS_LOV"."ID" IS 'LOV_ID';
COMMENT ON COLUMN "SYS_LOV"."MODULE" IS '系统模块';
COMMENT ON COLUMN "SYS_LOV"."NAME" IS 'LOV名称';
COMMENT ON COLUMN "SYS_LOV"."REMARK" IS '备注';
COMMENT ON COLUMN "SYS_LOV"."STATUS" IS '状态 - 0:停用,1:启用';
COMMENT ON COLUMN "SYS_LOV"."TYPE" IS '是否鉴权 - 0不鉴权,1:鉴权';
COMMENT ON COLUMN "SYS_LOV"."UPDATE_BY" IS '最后更新人';
COMMENT ON COLUMN "SYS_LOV"."UPDATE_DATE" IS '最后更新时间';


CREATE  INDEX "NAME" ON "SYS_LOV"("NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX3417659707300" ON "SYS_LOV"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

DROP TABLE  IF EXISTS "SYS_LOV_LINE";
CREATE TABLE "SYS_LOV_LINE"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "LOV_ID" BIGINT NOT NULL,
    "CODE" VARCHAR(50) NOT NULL,
    "NAME" VARCHAR(100) NOT NULL,
    "VALUE" VARCHAR(255) DEFAULT '',
    "SORT" INT DEFAULT 0,
    "REMARK" VARCHAR(255) DEFAULT '',
    "STATUS" INT DEFAULT 1 NOT NULL,
    "DELETED" INT DEFAULT 0 NOT NULL,
    "CREATE_BY" BIGINT,
    "CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_BY" BIGINT,
    "UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    NOT CLUSTER PRIMARY KEY("ID"),
    CONSTRAINT "LOV_CODE" UNIQUE("LOV_ID", "CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYS_LOV_LINE" IS 'LOV明细行';
COMMENT ON COLUMN "SYS_LOV_LINE"."CODE" IS '编码值';
COMMENT ON COLUMN "SYS_LOV_LINE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_LOV_LINE"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "SYS_LOV_LINE"."DELETED" IS '是否删除标记 - 0:正常,1:已删除';
COMMENT ON COLUMN "SYS_LOV_LINE"."ID" IS '主键';
COMMENT ON COLUMN "SYS_LOV_LINE"."LOV_ID" IS 'LOV主键';
COMMENT ON COLUMN "SYS_LOV_LINE"."NAME" IS '显示值';
COMMENT ON COLUMN "SYS_LOV_LINE"."REMARK" IS '备注';
COMMENT ON COLUMN "SYS_LOV_LINE"."SORT" IS '显示排序';
COMMENT ON COLUMN "SYS_LOV_LINE"."STATUS" IS '状态 - 0:停用,1:启用';
COMMENT ON COLUMN "SYS_LOV_LINE"."UPDATE_BY" IS '最后更新人';
COMMENT ON COLUMN "SYS_LOV_LINE"."UPDATE_DATE" IS '最后更新时间';
COMMENT ON COLUMN "SYS_LOV_LINE"."VALUE" IS '值';


CREATE UNIQUE  INDEX "INDEX3416806668800" ON "SYS_LOV_LINE"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

DROP TABLE  IF EXISTS "SYS_MENU";
CREATE TABLE "SYS_MENU"
(
    "ID" BIGINT IDENTITY(13, 1) NOT NULL,
    "CODE" VARCHAR(50) NOT NULL,
    "NAME" VARCHAR(100) NOT NULL,
    "PARENT_ID" BIGINT,
    "COMPONENT_PATH" VARCHAR(255) DEFAULT '',
    "PERMISSION" VARCHAR(255) DEFAULT '',
    "SORT" INT DEFAULT 0,
    "TYPE" INT DEFAULT 1,
    "URL" VARCHAR(255) DEFAULT '',
    "CSS" VARCHAR(255) DEFAULT '',
    "REMARK" VARCHAR(255) DEFAULT '',
    "STATUS" INT DEFAULT 1 NOT NULL,
    "DELETED" INT DEFAULT 0 NOT NULL,
    "CREATE_BY" BIGINT,
    "CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_BY" BIGINT,
    "UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    NOT CLUSTER PRIMARY KEY("ID"),
    UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON COLUMN "SYS_MENU"."CODE" IS '编码';
COMMENT ON COLUMN "SYS_MENU"."COMPONENT_PATH" IS '主页面路径';
COMMENT ON COLUMN "SYS_MENU"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_MENU"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "SYS_MENU"."CSS" IS '样式';
COMMENT ON COLUMN "SYS_MENU"."DELETED" IS '是否删除标记 - 0:正常,1:已删除';
COMMENT ON COLUMN "SYS_MENU"."ID" IS '主键';
COMMENT ON COLUMN "SYS_MENU"."NAME" IS '名称';
COMMENT ON COLUMN "SYS_MENU"."PARENT_ID" IS '父节点主键';
COMMENT ON COLUMN "SYS_MENU"."PERMISSION" IS '权限';
COMMENT ON COLUMN "SYS_MENU"."REMARK" IS '备注';
COMMENT ON COLUMN "SYS_MENU"."SORT" IS '排序';
COMMENT ON COLUMN "SYS_MENU"."STATUS" IS '状态 - 0:停用,1:启用';
COMMENT ON COLUMN "SYS_MENU"."TYPE" IS '类型，1-内部链接，2-外部链接';
COMMENT ON COLUMN "SYS_MENU"."UPDATE_BY" IS '最后更新人';
COMMENT ON COLUMN "SYS_MENU"."UPDATE_DATE" IS '最后更新时间';
COMMENT ON COLUMN "SYS_MENU"."URL" IS '链接';


CREATE  INDEX "INDEX3415720021800" ON "SYS_MENU"("PARENT_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX3415820871700" ON "SYS_MENU"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

DROP TABLE  IF EXISTS "SYS_OPERATION";
CREATE TABLE "SYS_OPERATION"
(
    "ID" BIGINT IDENTITY(5, 1) NOT NULL,
    "CODE" VARCHAR(50) NOT NULL,
    "NAME" VARCHAR(100) NOT NULL,
    "REMARK" VARCHAR(255) DEFAULT '',
    "STATUS" INT DEFAULT 1 NOT NULL,
    "DELETED" INT DEFAULT 0 NOT NULL,
    "CREATE_BY" BIGINT,
    "CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_BY" BIGINT,
    "UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    NOT CLUSTER PRIMARY KEY("ID"),
    UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYS_OPERATION" IS '操作信息表';
COMMENT ON COLUMN "SYS_OPERATION"."CODE" IS '操作编码';
COMMENT ON COLUMN "SYS_OPERATION"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_OPERATION"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "SYS_OPERATION"."DELETED" IS '是否删除标记 - 0:正常,1:已删除';
COMMENT ON COLUMN "SYS_OPERATION"."ID" IS '主键';
COMMENT ON COLUMN "SYS_OPERATION"."NAME" IS '操作名称';
COMMENT ON COLUMN "SYS_OPERATION"."REMARK" IS '备注';
COMMENT ON COLUMN "SYS_OPERATION"."STATUS" IS '状态 - 0:停用,1:启用';
COMMENT ON COLUMN "SYS_OPERATION"."UPDATE_BY" IS '最后更新人';
COMMENT ON COLUMN "SYS_OPERATION"."UPDATE_DATE" IS '最后更新时间';


CREATE UNIQUE  INDEX "INDEX3415000889300" ON "SYS_OPERATION"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

DROP TABLE  IF EXISTS "SYS_PERMISSION";
CREATE TABLE "SYS_PERMISSION"
(
    "ID" BIGINT IDENTITY(37, 1) NOT NULL,
    "RESOURCE_ID" BIGINT,
    "OPERATION_ID" BIGINT,
    "PERMISSION_CODE" VARCHAR(255),
    "REMARK" VARCHAR(255) DEFAULT '',
    "STATUS" INT DEFAULT 1 NOT NULL,
    "DELETED" INT DEFAULT 0 NOT NULL,
    "CREATE_BY" BIGINT,
    "CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_BY" BIGINT,
    "UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    NOT CLUSTER PRIMARY KEY("ID"),
    CONSTRAINT "JOIN_PERMISSION_INDEX" UNIQUE("RESOURCE_ID", "OPERATION_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYS_PERMISSION" IS '系统权限表';
COMMENT ON COLUMN "SYS_PERMISSION"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_PERMISSION"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "SYS_PERMISSION"."DELETED" IS '是否删除标记 - 0:正常,1:已删除';
COMMENT ON COLUMN "SYS_PERMISSION"."ID" IS '主键';
COMMENT ON COLUMN "SYS_PERMISSION"."OPERATION_ID" IS '操作ID';
COMMENT ON COLUMN "SYS_PERMISSION"."PERMISSION_CODE" IS '权限code';
COMMENT ON COLUMN "SYS_PERMISSION"."REMARK" IS '备注';
COMMENT ON COLUMN "SYS_PERMISSION"."RESOURCE_ID" IS '资源ID';
COMMENT ON COLUMN "SYS_PERMISSION"."STATUS" IS '状态 - 0:停用,1:启用';
COMMENT ON COLUMN "SYS_PERMISSION"."UPDATE_BY" IS '最后更新人';
COMMENT ON COLUMN "SYS_PERMISSION"."UPDATE_DATE" IS '最后更新时间';


CREATE UNIQUE  INDEX "INDEX3413502398100" ON "SYS_PERMISSION"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

DROP TABLE  IF EXISTS "SYS_RESOURCE";
CREATE TABLE "SYS_RESOURCE"
(
    "ID" BIGINT IDENTITY(10, 1) NOT NULL,
    "CODE" VARCHAR(50) NOT NULL,
    "NAME" VARCHAR(100) NOT NULL,
    "REMARK" VARCHAR(255) DEFAULT '',
    "STATUS" INT DEFAULT 1 NOT NULL,
    "DELETED" INT DEFAULT 0 NOT NULL,
    "CREATE_BY" BIGINT,
    "CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_BY" BIGINT,
    "UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    NOT CLUSTER PRIMARY KEY("ID"),
    UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYS_RESOURCE" IS '系统资源表';
COMMENT ON COLUMN "SYS_RESOURCE"."CODE" IS '资源编码';
COMMENT ON COLUMN "SYS_RESOURCE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_RESOURCE"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "SYS_RESOURCE"."DELETED" IS '是否删除标记 - 0:正常,1:已删除';
COMMENT ON COLUMN "SYS_RESOURCE"."ID" IS '主键';
COMMENT ON COLUMN "SYS_RESOURCE"."NAME" IS '资源名称';
COMMENT ON COLUMN "SYS_RESOURCE"."REMARK" IS '备注';
COMMENT ON COLUMN "SYS_RESOURCE"."STATUS" IS '状态 - 0:停用,1:启用';
COMMENT ON COLUMN "SYS_RESOURCE"."UPDATE_BY" IS '最后更新人';
COMMENT ON COLUMN "SYS_RESOURCE"."UPDATE_DATE" IS '最后更新时间';


CREATE UNIQUE  INDEX "INDEX3412860537300" ON "SYS_RESOURCE"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

DROP TABLE  IF EXISTS "SYS_ROLE";
CREATE TABLE "SYS_ROLE"
(
    "ID" BIGINT IDENTITY(2, 1) NOT NULL,
    "CODE" VARCHAR(50) NOT NULL,
    "NAME" VARCHAR(100) NOT NULL,
    "REMARK" VARCHAR(255) DEFAULT '',
    "STATUS" INT DEFAULT 1 NOT NULL,
    "DELETED" INT DEFAULT 0 NOT NULL,
    "CREATE_BY" BIGINT,
    "CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_BY" BIGINT,
    "UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    NOT CLUSTER PRIMARY KEY("ID"),
    UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYS_ROLE" IS '角色信息表';
COMMENT ON COLUMN "SYS_ROLE"."CODE" IS '角色编码';
COMMENT ON COLUMN "SYS_ROLE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_ROLE"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "SYS_ROLE"."DELETED" IS '是否删除标记 - 0:正常,1:已删除';
COMMENT ON COLUMN "SYS_ROLE"."ID" IS '主键';
COMMENT ON COLUMN "SYS_ROLE"."NAME" IS '角色名称';
COMMENT ON COLUMN "SYS_ROLE"."REMARK" IS '备注';
COMMENT ON COLUMN "SYS_ROLE"."STATUS" IS '状态 - 0:停用,1:启用';
COMMENT ON COLUMN "SYS_ROLE"."UPDATE_BY" IS '最后更新人';
COMMENT ON COLUMN "SYS_ROLE"."UPDATE_DATE" IS '最后更新时间';


CREATE UNIQUE  INDEX "INDEX3412099525700" ON "SYS_ROLE"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

DROP TABLE  IF EXISTS "SYS_ROLE_PERMISSION";
CREATE TABLE "SYS_ROLE_PERMISSION"
(
    "ID" BIGINT IDENTITY(37, 1) NOT NULL,
    "ROLE_ID" BIGINT NOT NULL,
    "PERMISSION_ID" BIGINT NOT NULL,
    "REMARK" VARCHAR(255) DEFAULT '',
    "STATUS" INT DEFAULT 1 NOT NULL,
    "DELETED" INT DEFAULT 0 NOT NULL,
    "CREATE_BY" BIGINT,
    "CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_BY" BIGINT,
    "UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    NOT CLUSTER PRIMARY KEY("ID"),
    CONSTRAINT "ROLE_PERMISSION_INDEX" UNIQUE("ROLE_ID", "PERMISSION_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYS_ROLE_PERMISSION" IS '角色与系统权限关联表';
COMMENT ON COLUMN "SYS_ROLE_PERMISSION"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_ROLE_PERMISSION"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "SYS_ROLE_PERMISSION"."DELETED" IS '是否删除标记 - 0:正常,1:已删除';
COMMENT ON COLUMN "SYS_ROLE_PERMISSION"."ID" IS '主键';
COMMENT ON COLUMN "SYS_ROLE_PERMISSION"."PERMISSION_ID" IS '权限ID';
COMMENT ON COLUMN "SYS_ROLE_PERMISSION"."REMARK" IS '备注';
COMMENT ON COLUMN "SYS_ROLE_PERMISSION"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "SYS_ROLE_PERMISSION"."STATUS" IS '状态 - 0:停用,1:启用';
COMMENT ON COLUMN "SYS_ROLE_PERMISSION"."UPDATE_BY" IS '最后更新人';
COMMENT ON COLUMN "SYS_ROLE_PERMISSION"."UPDATE_DATE" IS '最后更新时间';


CREATE UNIQUE  INDEX "INDEX3411367193300" ON "SYS_ROLE_PERMISSION"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

DROP TABLE  IF EXISTS "SYS_UNIT";
CREATE TABLE "SYS_UNIT"
(
    "ID" BIGINT IDENTITY(3, 1) NOT NULL,
    "PARENT_ID" BIGINT DEFAULT 0,
    "RELATION_PATH" VARCHAR(255) DEFAULT '',
    "CODE" VARCHAR(50) NOT NULL,
    "NAME" VARCHAR(100) NOT NULL,
    "TYPE" INT DEFAULT 1,
    "SORT" INT DEFAULT 0,
    "REMARK" VARCHAR(255) DEFAULT '',
    "STATUS" INT DEFAULT 1 NOT NULL,
    "DELETED" INT DEFAULT 0 NOT NULL,
    "CREATE_BY" BIGINT,
    "CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_BY" BIGINT,
    "UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    NOT CLUSTER PRIMARY KEY("ID"),
    UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYS_UNIT" IS '组织结构表';
COMMENT ON COLUMN "SYS_UNIT"."CODE" IS '编码';
COMMENT ON COLUMN "SYS_UNIT"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_UNIT"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "SYS_UNIT"."DELETED" IS '是否删除标记 - 0:正常,1:已删除';
COMMENT ON COLUMN "SYS_UNIT"."ID" IS '主键';
COMMENT ON COLUMN "SYS_UNIT"."NAME" IS '名称';
COMMENT ON COLUMN "SYS_UNIT"."PARENT_ID" IS '父节点ID';
COMMENT ON COLUMN "SYS_UNIT"."RELATION_PATH" IS '根节点到父级组织的全路径';
COMMENT ON COLUMN "SYS_UNIT"."REMARK" IS '备注';
COMMENT ON COLUMN "SYS_UNIT"."SORT" IS '排序值';
COMMENT ON COLUMN "SYS_UNIT"."STATUS" IS '状态 - 0:停用,1:启用';
COMMENT ON COLUMN "SYS_UNIT"."TYPE" IS '公司、部门的区分，1表示公司，2表示部门';
COMMENT ON COLUMN "SYS_UNIT"."UPDATE_BY" IS '最后更新人';
COMMENT ON COLUMN "SYS_UNIT"."UPDATE_DATE" IS '最后更新时间';


CREATE  INDEX "PARENT_ID" ON "SYS_UNIT"("PARENT_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX3409410755200" ON "SYS_UNIT"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

DROP TABLE  IF EXISTS "SYS_USER";
CREATE TABLE "SYS_USER"
(
    "ID" BIGINT IDENTITY(2, 1) NOT NULL,
    "CODE" VARCHAR(50) NOT NULL,
    "NAME" VARCHAR(200) NOT NULL,
    "WORK_NUMBER" VARCHAR(100) DEFAULT '',
    "PASSWORD" VARCHAR(200) NOT NULL,
    "SEX" VARCHAR(10) DEFAULT '',
    "POSITION" VARCHAR(50) DEFAULT '',
    "AUDIT_TYPE" VARCHAR(50) DEFAULT '',
    "HEADIMGURL" VARCHAR(255) DEFAULT '',
    "TELEPHONE" VARCHAR(100) DEFAULT '',
    "MOBILE" VARCHAR(100) DEFAULT '',
    "EMAIL" VARCHAR(100) DEFAULT '',
    "PASSWORD_DATE" TIMESTAMP(0),
    "BIRTH_DATE" TIMESTAMP(0),
    "ENTRY_DATE" TIMESTAMP(0),
    "WORK_DATE" TIMESTAMP(0),
    "IP_RANGE" VARCHAR(500) DEFAULT '',
    "LOGIN_FAIL_IP" VARCHAR(45) DEFAULT '',
    "LOGIN_FAIL_DATE" TIMESTAMP(0),
    "LOGIN_FLAG" INT DEFAULT 1,
    "LOGIN_SUCCESS_DATE" TIMESTAMP(0),
    "LOGIN_SUCCESS_IP" VARCHAR(45) DEFAULT '',
    "LOCK_DATE" TIMESTAMP(0),
    "TOKEN" VARCHAR(500) DEFAULT '',
    "LOGIN_FAIL_COUNT" INT DEFAULT 0,
    "REV" INT DEFAULT 0,
    "FIRST" VARCHAR(255) DEFAULT '',
    "LAST" VARCHAR(255) DEFAULT '',
    "REMARK" VARCHAR(255) DEFAULT '',
    "STATUS" INT DEFAULT 1 NOT NULL,
    "DELETED" INT DEFAULT 0 NOT NULL,
    "CREATE_BY" BIGINT,
    "CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_BY" BIGINT,
    "UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    NOT CLUSTER PRIMARY KEY("ID"),
    CONSTRAINT "CODE" UNIQUE("CODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYS_USER" IS '用户信息表';
COMMENT ON COLUMN "SYS_USER"."BIRTH_DATE" IS '生日';
COMMENT ON COLUMN "SYS_USER"."CODE" IS '登录名';
COMMENT ON COLUMN "SYS_USER"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_USER"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "SYS_USER"."DELETED" IS '是否删除标记 - 0:正常,1:已删除';
COMMENT ON COLUMN "SYS_USER"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "SYS_USER"."ENTRY_DATE" IS '注册时间';
COMMENT ON COLUMN "SYS_USER"."FIRST" IS '姓';
COMMENT ON COLUMN "SYS_USER"."HEADIMGURL" IS '头像图片链接地址';
COMMENT ON COLUMN "SYS_USER"."ID" IS '主键';
COMMENT ON COLUMN "SYS_USER"."IP_RANGE" IS 'IP地址范围，分号分隔，支持*通配符';
COMMENT ON COLUMN "SYS_USER"."LAST" IS '名';
COMMENT ON COLUMN "SYS_USER"."LOCK_DATE" IS '锁定时间';
COMMENT ON COLUMN "SYS_USER"."LOGIN_FAIL_COUNT" IS '登录失败次数';
COMMENT ON COLUMN "SYS_USER"."LOGIN_FAIL_DATE" IS '最后登录失败时间';
COMMENT ON COLUMN "SYS_USER"."LOGIN_FAIL_IP" IS '最后登录失败IP';
COMMENT ON COLUMN "SYS_USER"."LOGIN_FLAG" IS '是否可登录，0-长期锁定，1-可登录，2-短期锁定';
COMMENT ON COLUMN "SYS_USER"."LOGIN_SUCCESS_DATE" IS '登录成功时间';
COMMENT ON COLUMN "SYS_USER"."LOGIN_SUCCESS_IP" IS '登录成功IP';
COMMENT ON COLUMN "SYS_USER"."MOBILE" IS '手机号码';
COMMENT ON COLUMN "SYS_USER"."NAME" IS '姓名';
COMMENT ON COLUMN "SYS_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "SYS_USER"."PASSWORD_DATE" IS '密码修改日期';
COMMENT ON COLUMN "SYS_USER"."POSITION" IS '职务';
COMMENT ON COLUMN "SYS_USER"."REMARK" IS '备注';
COMMENT ON COLUMN "SYS_USER"."REV" IS '版本号';
COMMENT ON COLUMN "SYS_USER"."SEX" IS '性别(男/女)';
COMMENT ON COLUMN "SYS_USER"."STATUS" IS '状态 - 0:停用,1:启用';
COMMENT ON COLUMN "SYS_USER"."TELEPHONE" IS '办公电话';
COMMENT ON COLUMN "SYS_USER"."TOKEN" IS 'token验证';
COMMENT ON COLUMN "SYS_USER"."UPDATE_BY" IS '最后更新人';
COMMENT ON COLUMN "SYS_USER"."UPDATE_DATE" IS '最后更新时间';
COMMENT ON COLUMN "SYS_USER"."WORK_DATE" IS '登录成功时间';
COMMENT ON COLUMN "SYS_USER"."WORK_NUMBER" IS '工号';


CREATE UNIQUE  INDEX "INDEX3407390447200" ON "SYS_USER"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

DROP TABLE  IF EXISTS "SYS_USER_ROLE";
CREATE TABLE "SYS_USER_ROLE"
(
    "ID" BIGINT IDENTITY(2, 1) NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    "ROLE_ID" BIGINT NOT NULL,
    "REMARK" VARCHAR(255) DEFAULT '',
    "STATUS" INT DEFAULT 1 NOT NULL,
    "DELETED" INT DEFAULT 0 NOT NULL,
    "CREATE_BY" BIGINT,
    "CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_BY" BIGINT,
    "UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    NOT CLUSTER PRIMARY KEY("ID"),
    CONSTRAINT "USER_ROLE" UNIQUE("USER_ID", "ROLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYS_USER_ROLE" IS '用户角色关联表';
COMMENT ON COLUMN "SYS_USER_ROLE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_USER_ROLE"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "SYS_USER_ROLE"."DELETED" IS '是否删除标记 - 0:正常,1:已删除';
COMMENT ON COLUMN "SYS_USER_ROLE"."ID" IS '主键';
COMMENT ON COLUMN "SYS_USER_ROLE"."REMARK" IS '备注';
COMMENT ON COLUMN "SYS_USER_ROLE"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "SYS_USER_ROLE"."STATUS" IS '状态 - 0:停用,1:启用';
COMMENT ON COLUMN "SYS_USER_ROLE"."UPDATE_BY" IS '最后更新人';
COMMENT ON COLUMN "SYS_USER_ROLE"."UPDATE_DATE" IS '最后更新时间';
COMMENT ON COLUMN "SYS_USER_ROLE"."USER_ID" IS '用户ID';


CREATE UNIQUE  INDEX "INDEX3406723949500" ON "SYS_USER_ROLE"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

DROP TABLE  IF EXISTS "SYS_USER_UNIT";
CREATE TABLE "SYS_USER_UNIT"
(
    "ID" BIGINT IDENTITY(2, 1) NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    "UNIT_ID" BIGINT NOT NULL,
    "REMARK" VARCHAR(255) DEFAULT '',
    "STATUS" INT DEFAULT 1 NOT NULL,
    "DELETED" INT DEFAULT 0 NOT NULL,
    "CREATE_BY" BIGINT,
    "CREATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    "UPDATE_BY" BIGINT,
    "UPDATE_DATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(),
    NOT CLUSTER PRIMARY KEY("ID"),
    CONSTRAINT "USER_UNIT" UNIQUE("USER_ID", "UNIT_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYS_USER_UNIT" IS '用户组织关系表';
COMMENT ON COLUMN "SYS_USER_UNIT"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "SYS_USER_UNIT"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "SYS_USER_UNIT"."DELETED" IS '是否删除标记 - 0:正常,1:已删除';
COMMENT ON COLUMN "SYS_USER_UNIT"."REMARK" IS '备注';
COMMENT ON COLUMN "SYS_USER_UNIT"."STATUS" IS '状态 - 0:停用,1:启用';
COMMENT ON COLUMN "SYS_USER_UNIT"."UNIT_ID" IS '部门id';
COMMENT ON COLUMN "SYS_USER_UNIT"."UPDATE_BY" IS '最后更新人';
COMMENT ON COLUMN "SYS_USER_UNIT"."UPDATE_DATE" IS '最后更新时间';
COMMENT ON COLUMN "SYS_USER_UNIT"."USER_ID" IS '用户id';


CREATE UNIQUE  INDEX "INDEX3406114817300" ON "SYS_USER_UNIT"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

